from app.core.config import settings

Z_IMAGE_MODEL = settings.Z_IMAGE_MODEL

DEFAULT_RESOLUTION = settings.Z_IMAGE_DEFAULT_RESOLUTION
DEFAULT_STEPS = settings.Z_IMAGE_DEFAULT_STEPS
DEFAULT_SHIFT = settings.Z_IMAGE_DEFAULT_SHIFT
DEFAULT_SEED = settings.Z_IMAGE_DEFAULT_SEED
