import os
import weave
import traceback
from app.services.z_image.client import get_z_image_client
from app.services.z_image.constants import (
    DEFAULT_RESOLUTION,
    DEFAULT_SEED,
    DEFAULT_SHIFT,
    DEFAULT_STEPS,
    Z_IMAGE_MODEL,
)
from app.services.cloudinary.service import upload_image_to_cloudinary


@weave.op(name="z_image_generate")
async def generate_image_service(
    prompt: str,
    resolution: str | None,
    steps: int | None,
    shift: int | None,
    seed: int | None,
) -> dict:
    """
    Generate image using Z-Image model and upload to Cloudinary
    """
    try:
        # 1. Call Z-Image API
        client = get_z_image_client()

        # Parse resolution
        res_str = resolution or DEFAULT_RESOLUTION
        try:
            # "1024x1024 ( 1:1 )" -> "1024x1024"
            res_part = res_str.split(" ")[0]
            width, height = map(int, res_part.split("x"))
        except Exception:
            width, height = 1024, 1024

        result = client.predict(
            prompt=prompt,
            height=height,
            width=width,
            num_inference_steps=steps or DEFAULT_STEPS,
            seed=seed or DEFAULT_SEED,
            randomize_seed=True,
            api_name="/generate_image",
        )

        # Result is [image_dict, seed_float]
        image_result = result[0]
        seed_used = result[1]

        # 2. Extract local image path
        if not image_result:
            raise Exception("No image generated by Z-Image")

        if isinstance(image_result, dict):
            local_image_path = image_result.get("path")
        else:
            local_image_path = image_result

        if not local_image_path or not os.path.exists(local_image_path):
            raise Exception(f"Generated image not found at {local_image_path}")

        # 3. Upload to Cloudinary
        cloudinary_url = upload_image_to_cloudinary(
            image_path=local_image_path,
            folder="ramen-art-generations"
        )

        # 4. Clean up local file (optional)
        try:
            os.remove(local_image_path)
        except:
            pass  # Ignore cleanup errors

        # 5. Return response
        return {
            "image_url": cloudinary_url,
            "model": Z_IMAGE_MODEL,
            "seed_used": str(seed_used),
            "seed": int(seed_used) if seed_used else None,
        }

    except Exception as e:
        # Single exit point for all failures
        print(f"Error in generate_image_service: {str(e)}")
        print(traceback.format_exc())
        raise Exception(f"Image generation failed: {str(e)}")
