import os
import weave
from app.services.z_image.client import get_z_image_client
from app.services.z_image.constants import (
    DEFAULT_RESOLUTION,
    DEFAULT_SEED,
    DEFAULT_SHIFT,
    DEFAULT_STEPS,
    Z_IMAGE_MODEL,
)
from app.services.cloudinary.service import upload_image_to_cloudinary


@weave.op(name="z_image_generate")
async def generate_image_service(
    prompt: str,
    resolution: str | None,
    steps: int | None,
    shift: int | None,
    seed: int | None,
) -> dict:
    """
    Generate image using Z-Image model and upload to Cloudinary
    """
    try:
        # 1. Call Z-Image API
        client = get_z_image_client()

        images, seed_used, seed_int = client.predict(
            prompt=prompt,
            resolution=resolution or DEFAULT_RESOLUTION,
            seed=seed or DEFAULT_SEED,
            steps=steps or DEFAULT_STEPS,
            shift=shift or DEFAULT_SHIFT,
            random_seed=True,
            gallery_images=[],
            api_name="/generate",
        )

        # 2. Extract local image path
        if not images or len(images) == 0:
            raise Exception("No image generated by Z-Image")

        local_image_path = images[0]["image"]

        if not os.path.exists(local_image_path):
            raise Exception(f"Generated image not found at {local_image_path}")

        # 3. Upload to Cloudinary
        cloudinary_url = upload_image_to_cloudinary(
            image_path=local_image_path,
            folder="ramen-art-generations"
        )

        # 4. Clean up local file (optional)
        try:
            os.remove(local_image_path)
        except:
            pass  # Ignore cleanup errors

        # 5. Return response
        return {
            "image_url": cloudinary_url,
            "model": Z_IMAGE_MODEL,
            "seed_used": str(seed_used),
            "seed": seed_int,
        }

    except Exception as e:
        # Single exit point for all failures
        raise Exception(f"Image generation failed: {str(e)}")
